### ISSUE TITLE
Settings button

### ISSUE THREAD

**Issue by dahab49** [mmaheo/simple-weather-ios#1]
Maxime,this is a great app,which i enjoy using.When i tap the settings button bottom right of screen,nothing happens.My device is an iPhone 12 Pro Max,running ios 14.5 beta 2.My email please contact via this is,mukhamar48@gmail.com.Regards Muhammad

**Comment by mmaheo** [comment]
Hi Muhammad, thanks to use Simple Weather.
I tried to reproduce your issue, but I can't. I've released a new version last week, you can download it on the app store and tell me if you still have the issue.
Maxime
